name: CS-CoreLib
version: 1.5.13
authors: [mrCookieSlime, John000708, AlexLander123]
website: http://thebusybiscuit.github.io/

main: me.mrCookieSlime.CSCoreLibPlugin.CSCoreLib

commands:
  cs_triggerinterface:
    description: Background Command
    usage: Dont use it
