name: CS-CoreLib
version: 1.5.10
author: mrCookieSlime
website: http://thebusybiscuit.github.io/

softdepend: [WorldGuard, Factions, Towny, GriefPrevention, ProtectionStones, PreciousStones, ASkyBlock, LWC]

main: me.mrCookieSlime.CSCoreLibPlugin.CSCoreLib

commands:
  cs_triggerinterface:
    description: Background Command
    usage: Dont use it
